// divide the rucksack into two parts
// check for duplicates
// add priority
const ruckSacks = `
PPZTzDhJPLqPhqDTqrwQZZWbmCBMJMcsNmCBFWmMcsNb
vplSlfdfGvfRRGsgNcMglsFWMWMC
jtjvFHdjjwqrwqwL
NSffhsNSjfLjfstsjtjNNjjqMqnpggHngqgHGHCgClGbCzCC
dDPZZDZFdwFWwFZFWZRTFDwGzCMlgnpgCpnzglClHMbg
DTPFZQRcdTVNhbjVbcLc
JZLDcSZSpHHrrLrJcpzBRrhlzgRTmTmvBRmm
qQsQMCbMQWqCVVvmTRhTTRhCRhTg
svbGWPqGPNLJSpZnZpnN
wLtPGCLwfWLflCPtPfLLTSbHMbSgMdtvDHghhHvdgZ
nNsFznJcJqzFFszFqrNnRzdbZDDbRMbMdRHbMdgHvZSd
VczNnjsrFrjcNprqVwTPfjGllWPQBBWlgB
nnGtjFFjFTTTGtBGmWBTWffLcMJMQlzjQPCPcChCQDJzDJJd
SSggbHVbZRgZsHZRHdVhzCcJhzhMzJhQPQ
rHsNSsSZqqrNgpLLWmCfFGqGCBWm
ZnCtCCVZmVBCQBWQnWQNCQMcLrMMgMLqLSwMSSDwjcBD
hTbGJGfTbrSfScmjwj
bbGGlTdlJTdGlFpdFvJdsbmdZWPWtnVCHQvtVHzvtHWtCtVN
pNpCNFMNFhhwDgRVdSVqwgrdmJ
nvHbPZtTHWbntTmdTRrqVRrdmz
vHWPBWvntbWnHLHZLqWtBCjjhBNhCjGjjNjDNChlFC
CnFbFzpzJbsCRpbRpbnPCnJLTtwQtjdtcttHHHDtDPjQwTHB
qGrflmrNgvvmGqcdwrtWQHwTBHQWtj
mVMvSclGqvNVMMNVsZsnJJRJsbzpSJpJ
cJTcRllRldjZlFcbcFJrrvqCCVTNNVWSPpQNmpQqCPVC
wGLBfLzgBfzHGGGnLDGDGgwHqqHmVSWqpQpCpQRWVWVNpS
DRshRBLMhZlFZMJvlJ
SdGbmRGddMcfbWWSptssDHssGDNsjCCC
glPLTzczrCpNNsHTst
gqcZJPrBlhJgPndMVJbWMVfnWV
qNbmLmndBQqjsCPLZsLPZz
pwfhfCvJvvTMGzSjzPSPjcZp
VvvJVMCrvTRwgvwWvqNmqblNHtBWqQWlql
WNJmddmpFmMMrnlFddlWTHCHBRcnCBTRzTDRTwTz
qffLvLLvbqhqPbjbqRGPSqVtPDTTwTwTDzCBCccQczssCwcc
tfhGLhqthZVhbfpFRJMMMrJrZpmZ
VVgSmdqFpMddqSfpfVVWQvzTPvTWPrpsQPQQJv
ZCnRCDwRWCPrTrsW
HwRNLLsnHRNjtRSqNqMmfqVVMbqg
slqwzGvWqMsvbmTzTCBhhBhgcgjbCPCchc
tJVJSZStQdMQSdntJHjFNFPCNpjFCPcFFdhB
QDrRVZSnrQDVVRRtRHHWGmzTDDqMqMfzwswWsl
rFBrJFcrWHzCLFHqSg
PdVjfjlGPRzRGtGLRC
TQPMpMVPDDPfPTMMPpTWWrhbcbTcWbzzcsmTmb
ZDQDZDJNqqNbwQPgtlGntHlVGlPPrf
vhmChcgvMCdvzCvvHfdntBHGBldrHBVG
cCpTCLvmjhpjzSTTLSpwbDqjJQFZgNDwJssFDw
LfMFLwMwdrFmWBJD
tVlHqqVTHRtmQggrjQqDJg
VDntHnDGRntHPbLPPLLZhcsLPLww
FBLddLctDQcbCLltbdCRdLQVNVDjnPHVnsjnPqVSHNNVTP
vGmwrZZWJpfWfmvZgZJjSTPqsTrVPTrHTssNPP
wNZJffhNWmhvMhgwMZpvNJtbQRtQQLdFhbQFClLBCBlc
npvSWJBCDDBBDSvCZSpJdsTZsRhTdgMgPdhqHHqR
bjtwqLrtmfmtLVjVLQHHHdgwTTHMssMTGHhH
VtmVVNtqlllpJvnnnS
nCqrnLSSGnpjBjBGbcbPbB
vfdVdtdgMMrFgHfHPcBcPBjwQDjFbwDB
zgHWMmgHmWfWvVvRRzLCSCJsZNpJZSsrnssW
bBjWlfrrnClSssMMFmVVhMjgMpLM
dRDqDdzQrDdhqMMPtVLgFL
THDRwHDNDdQdcDvTcZbBGBGrZZnZcrlb
jgSVPVsVmshhsCQm
vmFtcDBfDFLrvTFZvLFvWzWhHwCWHnwHnCQCcwnq
FmDpFBmZZFrDbDfDtmLNgMPNGdPjRdPlPPpMVN
VVJGdSHZnnHdgFntcschhccvvPvtstPq
mLNjNQFBpPlPvNqs
LMTMMRDwwMMSGZzRnnGbzF
JFFfVrvVmHfGmHFvmrSQBQlSJLlShLlgBqwJ
DMCdpCbtgbcCCNpbCCPgRqdldBRQRBRwLsBSLhQs
cgbcPbpcWDWjNCZDWWZttDDGrHzznHzjGzmHnVjVvvVnrz
rtGTmSTGNtvvgfNGSbfwWWvJqwcDwwJPWcwWqD
lZhdHzFhLZhdBcWsWsWmwPcFqW
BhhjLzhZCCdhgCTtCSMmMrbt
FrzSRNrWNFdNhcRDDdrFWCVVZZZmjJbJSPlllgllVbgT
nQGGHqvHMVVpMLGffqtwLMtwlmPbTbjZPJmllLJBmZmZlZbP
VMvvpvQttHqnsvhhzhdrcdWNchsW
BzRTBbWVQNdngtDFVprDFrpF
vhfhSJvbhwSpDDFZHfMpHp
JhmvJsLLJLJqmsJLbsGGjvNRzzBcTBNlRNmnRTQdzzzn
vpCLrTcpRmncrncLcnccvLLNWVsRbhbtsQbJbVQWtWlWbW
PfFfdjdSjPffMFsQbNhlFssFNQ
zBDsjgfZHczLHTHC
BnvpJnVgPWJzczpnvnWVWRGTrRTGmmBhRmBmThrmrf
dNlwjLNLlbLSjLQVdLdjjSTRHmRmTTNmmRRtfTTfhThs
FSSSqbVDQZzzPPPFZc
fTTrrBqwfDTWfTDrRNrnRjgPSpJPnnmp
PvHPbsvZlMtbbvbCLLMHtHZZjtgJRjSnJSpSpjRgRjggSRmn
VLHbCbVPLZvlvMhHCHlPHbLCqQQfdQTBddTWhDTBchQzQwBW
ZBHHfHWLfLqjfLjHZBSDwHDWhvpFCQqNpvVNVNQCFPJvPQCF
zMrtclbdvFPSpdFp
rGMMnnGgsbzblRnlSrzSgRRDwLWjLjTTDBZmfLwZmDBf
rfJVfnztTfZFMfZq
cRGcdddPRbHvHCRHRmShqFrPSTmTPjSjZT
NvRHGGdNLrNJsDtL
dgggppRqnlnjbbjRwzmtHb
ZTPhrVvMZhrVQPZNCMZQjjbFtjmswwFtzVmLGbmL
rZhPCPPcNPNTMfvZPCvhMPSBpgSqSqfpDgJJggdwWJgg
TsgFbTQSZZsSJFThhggQFshpMSzRRRDPwwzPwDftRDrczLww
GCmnjCNjmlVdHNfdGNjMwPrrLwLcMcrcRHzMHM
nmmBnmlWlVWvjnNlpfFQbZsFpQhgJFpB
jfpdTTqqJpDfQrscgsDh
mNFmHHtVsVQrsllG
CmFtZPHNzzpBspzpLBqw
RsgJsjsZbTjmZZMMJPtCSPPDhCSrDhrjhC
lBwzHLQddZlLQnChGdtDhrnqhq
fLHpNQQpwvHllQVQHNNfHpzZMFWbccmTcbJMcFsWTRVbsTWF
DhHFMRDDmLmshTmSCpSWZVNHtCCNnW
fJJPBvlvlBflQQfQtNWtQzpSWZNtCZpN
vPJbdvBfqhqhShTFMs
lttWShphLtWWGppCQLlwZTHZHmfjjvwvHFmw
MFNssMMDVzrrnTmvJTHwJmZmZr
MsBznNznRgzzncFBLQQGGBBtdhdGpWPp
JFmvMWBmBlbBCZrZrH
DjRRjgffgjqwsDqrcHNNbCZbCbbN
sSffwRVjjDVzfjSjswDSQLdPrvGvFMmMJMMJmnWzGL
RbvwgbTVgzGTrhvWDmNDGJfCDffMmNBD
PjSlqldccqFLSqQLCpJfpWDCcCJZBpMD
jlHdPlqqSnjHggWgwrhzRz
WsJnWnmCJpTnLWmJLCSDVVmhNjRbrDRgrgZRhrjrhhgdZN
QlFfQBqlBwBqBffMFPsbgdgwsrZjrPNrNs
MvvvlHBcfBtvffGBcMqqqLpmLsJtpSLSCWCVCnnTzJ
QSRRwSWPhWhwwHbtsNGZNRNZTgRcmc
nfvDCrnnDvJJDDVMLNgtsZmZsVtZGgqmGp
nCngDlFfvvJLnCJJLMFMClHBBzQzwzbhlQHHPllbBhdb
qNFzGFFFnGGDJnzSdFdzjdvmCvzPzzRmgCmMmtgvcmtV
sQlhpLpWQQZpQZpQrBlLsLLCRggtMgVbbtggBmVVmbmBVm
ppQHRflRSGTdHSGN
BgTnWbbwPgPWgPGfGlWfdFFFlsSF
QvDNDZRMjCNZcHZZDQFShGFpBhdRsGpLsFRd
rrqvNcHjBcJgrTzbPVVz
pCjdsSdCljdBlpJpdmjHFHmDfTDTwgfgcw
WQrWnGzhNZzWfcnHfBwnvwHc
RLGNGQhWZhMrZNtBpsLPsVJbPLVb
TRDDSzNhHNHfSppCCMZsMMssdgZvfZ
GbGlctGqrBqVtrtLGtmqTtssPdMZcCZMnMvCZgdddgsP
BQqbVVVqLtBqWbTlmLBhQjFhJDRpHhzpJSJDNF
FTHTnPSmFqSPCTVDhZRCZDhjDRsV
blbLcBgMgMlrcLMbzrlBLZjRVsZZfNVfVfJsbNqDDh
tLtLQgzWMzSnHmPSWdqW
DnwmFcpmpGqFwCwmfCDMZsNVVMdlVrsNsczrrl
ghtBPJbHtWPbJPdBSPMzsrTTzZMTTMSNzrVZ
bPdjjhtPPJjjBQJJdbhRgJhLCnfLGGmLnGLpLfDRGGfpqG
HzzZZjCLjjZCmVQppssbGpmcTGgp
nMnJPqJlMPqBJllSJvlMSDGGBcgBcsfBhTpsFhgTTfFQ
drSRqnSqJDcSJrMJnRvCHtWZtjZZrHtVjrwZLj
mDJjmQggstPvDWJgQWJgPPmNFFLZpphZNlNpZLhSLvLZNf
rzzfTczCzCdBwddcCCHFpHFMNHZSHMFrHNFp
bcfzdGnCtVsVtsWn
CMfCfGfwbMMLdTMH
lqzDgLWqQWhQNWnlQqHTFFFFchbddTRbSddd
WnzDNZmPZmgglNCrvjrtrLffrJZJ
BllCMzjjlBHCCllHvljCMhbrQbTVTrvprTqrFWFFvF
ZNwfNLRnfwtRtNwqThVFpwWVJrbh
LnRnpNRSLcpZZNtmZmjgGgGMPBHCmMzsmsHM
MRMPpwWTLMMMMLLRMPbvfQZCnqQnqvWZWGqGDQ
gJslgmlmSZqssGGbnV
mJFSmmjcdmgJhdgrdjcdjwbRwpMwpHBRHrztwtRMRL
CccctqnQVvQcrsFwznmnrBrs
LLPThTSjPdJjLTtMBrsDmbbsBwbswGMF
jLSLWPLlTlgSlgSghdvtQZvqvWRcCpHVCqWp
DmggMZCDbdNrttnbPn
cclqSqGjSBwLqswNrFNzffFfNPsCsd
jGpLBcwlQBSpLjSQLvjRTZHTCRRDggRTHhmvmV
LWzrnwZFnzQlWQZndWFNvHBNDVBBNjplNjjVvV
RCSmPSCgsgTmCRqnsTCHvjJJpvBBSVSMpVjVMJ
sfgsRGnRTghQWWbLwfhF
JnJlTnDnwtWHMdJt
phNPDPVvPcPPvMRqVZRWMqRRWM
fGGScQDfssQzLbgT
rLVVdSSvVzQSRnzSRRnBQMJqDTjMsMsMqqPPhP
wmbWWFGVlGfptbhshsTmhqDPJJMm
CbWtWlCNpglgbtCWtFHdvNHVZnZZVnNVHHcc
qtRszqSZVnTCVwwLJpcgppLHqp
MPvBGNnDWMGMPDvGBPvMBFvpppjHwHpJJJJJFjjwLcjLJg
hBfPNvGvhDnvMPdslCZCtVsRRCSZff
HgvgvLNDcCcNBPDDvNNBzLNBnnhQqwRnRLQhWRhhWssqsnZZ
FlfprJzttrrTlGpbJVQhRwwbnbsRWVnZss
FGmdJrFdJddmjFfTttpfftlDvHSDgCDHgvSgHPcBzMHSzj
dgHhCJbBbwgNcVzlvzvzQVzH
RZPjRRRDPnjrjSnfFrDsnvzWVlzLfGzvBVWccclcGl
nDDZPjjRnZmFstnZBrsZgtCgbtMdqbJdNqMdgdwg
LvdrGnDBGBGrvrGLJtdrmmcfClqllsqlmjsLmcQC
VpbwbwTSVVwpzZMRSVmsjDqCclclNZCjNjQq
PpzWwRMwTwFpwtJBHnhtdnDvvP
GCJSClmwzmSgrpPpSpgcrS
bjLpsspHMHvBTsDLjTDtbTBFRFrQQQPcgQgcFcFPcFcnPs
pBTBvqBHbDjHfJqlGlzWJGllWC
GgbGNjQGzzQvFcFfRFmFJbff
pHDSLLCqpqppPZVSCSDdncRFwfmZcRWRJfncmRJn
LDTTLSSDSMQgvNTmzz
bLjgLVlJnjSJjgLgLjqqMcMfddftcCCnCccfQfsC
FRRmphNRmmdwPHpBPswDftDzMCfMcfWMMC
FrvdvrPPFHhNRPvFRmFZVbggqbGjJglJbjjTrVjJ
cSpdczpfRQQGNGGqvGHv
wPwFPhCFWbbmChwWmhFPsWrsDVwqVqZqvVVVvzGHDZqHqtZz
gbPznCbPmmWrWbWhJRpLnLRnTcScRSSLBd
pfwbrjTbDczbzbPcwTQbvWdWWTdddSldVHWSgHgn
mQmFQRFssJJJJthtJmBJmCHMdlWdnlltnHSVlSlgtnvM
BJBhRhRqRLRJNhJhBDwjzPPPcNQZrZrzDr
HTHwQJzwLZNcTwJtFRFHDtFvRFRFdr
jlMnMlbqqpMBvsWBVGRRGdSVgrDthFDddh
qvMjjMMpbPWqmMjnlpplpnWscNwLCQPzQLfzTzcZJfLQLPJz
gCTHTVdPdPvFfdCCSScZSZncMMCGGM
LNqLlssmWlLqzBRzWBwWBRRZdmJZcSSQDncnJtQcGDDDMd
jszNLwNWRRrzNbhbvHpdTjdvfH
NgDWhQmhfFlWFWlzDfhpBwfPBBdwwBJRBPqJJB
HHMCcHtGcMMbSGjScMGLSsRnqdJJlqqpCPJBRpBRdp
trMtLVtjjVtjttGctrLLTlZmgFzZTZzZNQmzZDNFhgFD
MBMtFzBnzSJJttSZBNNZfTsPqTqqqNZNPc
LlQDQLVCwCDbfRCmRGVjCwLLcqslNcNPgqgTPTsqNNsvqHqs
RfffRmdjnnzpndtr
nzpnDRDVwRRjVTSlTtlSSCQLDC
vgZHFBbbfCbvFbrFSSTqqcGtGTtBGQqS
HggMfPfbFZbPvNvgZZdHsnJjCzphzVwJjsmpmjMw
FgvgrgDpRDGTTWVDVd
zmbnNhHHQHshhhcbnHnnbBTMBMLLWLLGMqWLfzLLTV
mnnQHjcHHJmnNcHnnhmvZpRrCVZVZFrRJZVPFr
ZhpVhCSHbsCPbnmF
GBWGGrftTJlrfttQqsVPbPnGjDszFVncsG
qfMlQJWBrNWQfftqrQqBhRvdVVSNVSpZdvSZwZRS
mfzRQqMrtCwLMMZM
sbVbWgFdJCldtNRPNZ
FpggcgsjJccJVJJJcbbWWGrHnfmBnrHzfnfzvqrQmpfR
rWvbrfLnHHnzlFrFWWzJfRQQTwbwRQmQQCgQTwQBwg
MPsqcZpZdpjGMptpqCSsSwRNjQTBhgwhmgwgmmwgBm
SZqqqCDGMtpMFFDvFHfJlvDJ
RZnrZLZbLjRZwdlrnbLClCHMNCTlMMWBPPTHlT
SDgDzQDcfzJBNPssWCwSMN
fpQJwmmQmjhjGRbr
jQzqvLzvMTTQMMSS
VJlSrnBRZbbJbVnWWBlVWRCSNTMppMBMmmNPHMcNBmTMGmHp
CtDZJllRClbFzLtszhqFqS
VwcwzBdmMzJSdMBzzGndGSmlbqbgZgfblTJrTbrqZbTlTb
tRDvCvCRDCDWtPjCHjvDWTgZLfNqclZTTrNfZtLbLc
DDvPhhRRvjFjHPRjvVdMwhnpwBSGcwSGcc
LRtLJSNLdNLjNLRRNdRzVmVrggWmmmpVmpVvBBWFvm
wqfZnsMnhCnlfGPCCqwphJpWrFHBWHrvTrTHTH
ZsbGsflwGtjJbzLLjt
MjdFCjzsQFJQjzbmWHHLPPTfvsLfPZ
cNgpBgplzVvPTvmLPTVm
qNlqpcNtBzjQQCQqJjwJ
cczNGcgNhztlGPCCLDpBSpfVDpCJpSpBWs
nFqnwrRQrHnFHTMnZqQwMnmFsVsfbSSSJBSsfVVDfWVBWbVm
RRFZFMHjrQMjrHZqRjLdchdGtGjzDLgtzN
tzFmNfFNmFclrffhNtNlDWRSdFWnJCnRvRjvJvjD
LMgZgpZLMpPPPVPMMPbjbndWJSnWbWHWSCRbJD
BLwMpgMPgwQpTgTTpMVZMTftcGhhhtrhhcGGzQhsllCN
DWtHFWDHtwsWFHWDWwQblVgnllRBnjvBlVjRVbll
TzChCMGfNhZSLhLhzRRVvvjmczRgvRmv
pZSGpNJhCNGLSNLfMGJfJJQFrDDQDqHHgHpsWPFDttQW
qqccVQZWBVfjzzPVDMJtDtNccCgmtCCm
lvBRHBRGRDDCRmnmbD
SLFpGTSsTSsLFsHGvLvdGvdVwZBzZqqzjdQdZjVfrqwW
dLLwHLTWwjMLRZHCHZglDvjgvvNNDssSsmmN
nPfJPFbnhMJQfnpJGQJfQBBVssglsmsVVmBDsSqDgvNlgv
FbMrPPhrtGbJpnhJpJFFbbpJcwtdZzHZZwHCZdwctzTLcHTw
hCfzfLVbShRwRlBjdzmz
JZhrMMhZgvHFHJnHGgWdpmpnmlpRwBndRBwcBj
rMHFhgHZqtGvrWsbPfPNSbstTffN
dSwQQdSlHtlVQtqqrMZbFBRnBfZRMbDwMw
GTpcgLcvWvGvJzGpZGJpWpfmMWPBmDPRFPMFMmBfbFFW
hpcGhTCsGspLchGGzcpvZNStQHSSlNjjtlttlQsq
nJlhHlLlJGlRnMSsMLsnsSMwFHgwrTBFFwjBjppgpqfwqf
QmzzmbzNcZQQzDVZDcZQNDtzRqRBFTqTjjwpjBBNRrpBwfww
mvQPbQtttVVDzvzmRWCWLhSSslvWLGlW
nSpdSDPpRdrNBhMBMSJJ
bzCTcwzbczCZswMssczmCCgcqBmrQrrmBmqJBVBVNtrVttrq
cvzscgZzwTCsWsZvwTfzljDHnflMGMMndHFDdRPp
sDDnzLVnsMtjnDgfSSbfBjggbqBC
rlrlcppWcGdPrZNccJrSBSmCHqbSqCbSCgCHPq
NWcZgpFFgFpDFnDvtMDFzz
ZpczTjpZcnncHFDn
hSqqJWWWRRhlnFDVSFnQCB
qhNMWfqfMhJJRLRvppDzNZTpPTvwwD
rbSDCwPWwPVcSHcwHspNpNsddszmwGtswN
vBBfgQvBMvMvjLLlllqtBTNNTPPzTztTsRNPTt
vvQnjlMjjjqJqQLSrcDcPWbcHbDrDn
BphwqbwNsjsNsBdDjjhGpsGWzMMTWRTCflfDWSSzfzSlWf
cFnrrHrnZVZQQvFFVvZhRzTCWlSRMSWhZMWt
HvJVvggHvVrmQLqmNqLBbhsssw
NcBqSjGGBjNbZcHwhRVHPwPwPlZR
TvdtdtvFgHwWgdhn
tMJFTvtvFtrLJMHBqNNBzjrQcjqNmB
RrQfLfQvMFdQvLLQVfFcnbSbnwVSnbDslsbSDzDD
PHLjmHqqZCjPglsbwJbqnDbbJl
LNHLhjBHHGRfphphrtfh
FcdMchqcgdchqcfcNWWghNrRrVRjGHFjDJmGFDrRVGJD
zQtvBvtbQzpSzBptzbBznnwZJRDRVmVnGRGrDrHjZGrr
HLspTpQLBqWqLqcNgM
rnqbSSQhsshFqQQnsPSnhbnrzHzzHLNvLHCLFCvVJTlNLJTz
fcffljGBwgmwwftzNdCCdvLvtHNLTH
BjWgMGjjWZMwjjgwgMWpwPlnnqSnqQhnrbPMRDsqQs
hRJhFdNJcrbqbbMF
qZlTTgTvlHnqvllPssQrgQcQwscrQMsf
CClpSnTllZnZCDLHnlNzGSRmRthVmmzqJzhd
DLzSMtDLtzmmlDlMlMDbcrcTDqFvVvVqqTbD
dnZshHpZRChgnszRwRZCpTqqTcwVqFcrVqcBVPqVTr
snRRRdJsZgphCWlWtmJSjWWzjt
`;

let testp = `
vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw
`;
// charcodeat < 97, is capital, 97 - 122
// caps 65 - 90
let total = 0;
const sackArray = ruckSacks.trim().split(/\n/g);
let r = sackArray.reduce((accumulator, currentValue, currentIndex) => {
  let ar = accumulator;

  if (currentIndex % 3 === 0) {
    if (!ar?.[ar.length]) ar[ar.length] = [currentValue];
  }

  if (currentIndex % 3 !== 0) {
    currentValue && ar[ar.length - 1].push(currentValue);
  }

  return ar;
}, []);

for (i = 0; i <= r.length - 1; i++) {
  let ele = r[i];
  let firstEle = ele[0];
  let duplicate = "";
  firstEle.split("").forEach((el) => {
    if (ele[1].includes(el) && ele[2].includes(el)) {
      duplicate = el;
    }
  });

  if (duplicate.charCodeAt(0) <= 90) {
    total += duplicate.toLowerCase().charCodeAt(0) - 97 + 26 + 1;
  } else {
    total += duplicate.toLowerCase().charCodeAt(0) - 97 + 1;
  }
}

console.log(total);
